### ISSUE TITLE
TODO 리스트

### ISSUE THREAD

**Issue by nosorae** [nosorae/ImageFactory#19]
- [ ]  난이도 중) 업스케일 후 전후 사진 비교 보여줄 때 전 사진에서 에러 발생하는 이슈 해결
- [ ] - [ ]  난이도 중) 예외처리 - {"status":"error","messege":"Lora Model not found"}
    - 모델 리스트 api가 type구분을 제대로 해주지 않아서 발생하는 문제로 컴케로 해결해야할 문제
- [ ]  난이도 상) 결과 이미지링크는 24시간 지나면 사라지니까 결국 업로드 해야함.
- [ ]  난이도 상) 결과 이미지 여러장 보여주기
적어도 사용자가 잘못된 type으로 요청시에 어떤 행동을 취해야할지는 알려줘야겠다.
- [ ]  난이도 상) 디버그 모드에서 스크롤 버벅거리는 이슈 수정
